#!/usr/bin/env bash
# Ensure Cursor SDK bridge is running on the host for Docker dev-agent.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -f .env ]]; then
  echo ".env not found — skip bridge setup"
  exit 0
fi

if ! grep -qE '^TELEGRAM_DEV_AGENT_ENABLED=(true|1|yes)$' .env 2>/dev/null; then
  echo "TELEGRAM_DEV_AGENT_ENABLED is off — skip bridge"
  exit 0
fi

if ! grep -qE '^CURSOR_API_KEY=.+' .env 2>/dev/null; then
  echo "CURSOR_API_KEY not set — skip bridge"
  exit 0
fi

PYTHON="${ROOT}/.venv/bin/python"
if [[ ! -x "$PYTHON" ]]; then
  PYTHON="$(command -v python3)"
fi

PID_FILE="${ROOT}/data/cursor_bridge.pid"
SOCAT_PID_FILE="${ROOT}/data/cursor_bridge_socat.pid"
LOG_FILE="${ROOT}/data/cursor_bridge.log"
PUBLIC_PORT="${CURSOR_BRIDGE_PORT:-9247}"
INTERNAL_PORT="${CURSOR_BRIDGE_INTERNAL_PORT:-19247}"

if [[ -f "$PID_FILE" ]]; then
  PID="$(cat "$PID_FILE")"
  if kill -0 "$PID" 2>/dev/null; then
    echo "Cursor bridge already running (pid $PID)"
    exit 0
  fi
  rm -f "$PID_FILE"
fi

mkdir -p "${ROOT}/data"
export CURSOR_WORKSPACE_HOST="${JOBPILOT_HOST_WORKSPACE:-$ROOT}"

echo "Starting Cursor bridge on 127.0.0.1:${INTERNAL_PORT} (workspace: $CURSOR_WORKSPACE_HOST)..."
nohup "$PYTHON" "${ROOT}/scripts/run_cursor_bridge.py" \
  --workspace "$CURSOR_WORKSPACE_HOST" \
  --host 127.0.0.1 \
  --port "$INTERNAL_PORT" \
  --daemon \
  >>"$LOG_FILE" 2>&1 &
BRIDGE_PID=$!

for _ in $(seq 1 30); do
  if [[ -f "${ROOT}/data/cursor_bridge.env" ]]; then
    break
  fi
  if ! kill -0 "$BRIDGE_PID" 2>/dev/null; then
    echo "Cursor bridge failed to start — see $LOG_FILE" >&2
    tail -30 "$LOG_FILE" >&2 || true
    exit 1
  fi
  sleep 1
done

if [[ ! -f "${ROOT}/data/cursor_bridge.env" ]]; then
  echo "Cursor bridge startup timeout — see $LOG_FILE" >&2
  exit 1
fi

echo "$BRIDGE_PID" >"$PID_FILE"

if command -v socat >/dev/null 2>&1; then
  if [[ -f "$SOCAT_PID_FILE" ]]; then
    SOCAT_PID="$(cat "$SOCAT_PID_FILE")"
    kill "$SOCAT_PID" 2>/dev/null || true
    rm -f "$SOCAT_PID_FILE"
  fi
  echo "Exposing bridge for Docker on 0.0.0.0:${PUBLIC_PORT} → 127.0.0.1:${INTERNAL_PORT}"
  nohup socat "TCP-LISTEN:${PUBLIC_PORT},bind=0.0.0.0,reuseaddr,fork" "TCP:127.0.0.1:${INTERNAL_PORT}" \
    >>"$LOG_FILE" 2>&1 &
  echo $! >"$SOCAT_PID_FILE"
else
  echo "Docker proxy will forward port ${PUBLIC_PORT} (service: cursor-bridge-proxy)"
fi

# Rewrite env with public Docker-facing port
BRIDGE_TOKEN="$(grep '^CURSOR_BRIDGE_AUTH_TOKEN=' "${ROOT}/data/cursor_bridge.env" | cut -d= -f2-)"
WORKSPACE="$(grep '^CURSOR_WORKSPACE_HOST=' "${ROOT}/data/cursor_bridge.env" | cut -d= -f2-)"
cat >"${ROOT}/data/cursor_bridge.env" <<EOF
# Auto-generated by scripts/ensure_cursor_bridge.sh
CURSOR_BRIDGE_BASE_URL=http://host.docker.internal:${PUBLIC_PORT}
CURSOR_BRIDGE_AUTH_TOKEN=${BRIDGE_TOKEN}
CURSOR_WORKSPACE_HOST=${WORKSPACE}
EOF

echo "Cursor bridge ready (pid $BRIDGE_PID, docker port $PUBLIC_PORT)"
